system/adb: Download the latest package
to fix error: microADB/hal/hal_uv.c:32:38: error:
a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]

Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>