cmake(fix):bugfix fix missing include path for aiotjs
in file included from /home/work/ssd1/workspace/mirtos-ci/nuttx/../apps/frameworks/quickapp/src/framework/cdp/cdpprotocol.h:12,
                 from /home/work/ssd1/workspace/mirtos-ci/nuttx/../apps/frameworks/quickapp/src/framework/cdp/heapprofiler.h:3,
                 from /home/work/ssd1/workspace/MiRTOS-CI/apps/frameworks/quickapp/src/jse/quickjs/jse_quickjs.cpp:11:
/home/work/ssd1/workspace/MiRTOS-CI/nuttx/../apps/frameworks/quickapp/src/aiotjs.h:10:10: fatal error: app_interface.h: No such file or directory
   10 | #include "app_interface.h"
      |          ^~~~~~~~~~~~~~~~~

Signed-off-by: xuxin19 <xuxin19@xiaomi.com>