examples/watcher: fix compile error.
watched.c:77:21: error: implicit declaration of function 'getpid' [-Werror=implicit-function-declaration]
   77 |   int watched_pid = getpid();
      |                     ^~~~~~
cc1: all warnings being treated as errors
make[2]: *** [/home/work/ssd1/workspace/Vela-Multi-Boards-dev-system-CI/apps/Application.mk:253: watched.c.home.work.ssd1.workspace.Vela-Multi-Boards-dev-system-CI.apps.examples.watched.o] Error 1
make[2]: Target 'all' not remade because of errors.
make[1]: *** [Makefile:52: /home/work/ssd1/workspace/Vela-Multi-Boards-dev-system-CI/apps/examples/watched_all] Error 2
watcher_main.c: In function 'watcher_daemon':
watcher_main.c:195:17: error: implicit declaration of function 'getpid' [-Werror=implicit-function-declaration]
  195 |   watcher_pid = getpid();
      |                 ^~~~~~
watcher_main.c:218:7: error: implicit declaration of function 'pause' [-Werror=implicit-function-declaration]
  218 |       pause();
      |       ^~~~~

Signed-off-by: wangzhi16 <wangzhi16@xiaomi.com>