graphics/lvgl: fix build due to no-format-security
Without this change the build produces error:
  error: ‘-Wformat-security’ ignored without ‘-Wformat’